.\" Copyright (C) 2012 L. Guruprasad <lgp171188@gmail.com>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License version 3 as
.\" published by the Free Software Foundation
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH cows-and-bulls 6 "2012\-07\-22" "Cows and Bulls"
.SH NAME
Cows and Bulls \- A word guessing game based on the 'Cows and Bulls' game for numbers
.SH SYNOPSIS
.B cows-and-bulls
.SH DESCRIPTION
Cows and Bulls is a word guessing game based on the Cows and Bulls game with numbers. The game chooses a word of known length and the player has to guess the word by guessing words of the same length. For each guess, the game tells the number of cows (the alphabet in the chosen word present in the exact position in the guessed word) and bulls (the alphabet in the chosen word present in a different position in the guessed word). Based on that, the player can improve his guesses to come closer to chosen word and eventually find it.
.SH AUTHORS
.B cows-and-bulls
was written by L. Guruprasad
.P
This manual page was written by L. Guruprasad <lgp171188@gmail.com>, for the Debian project (but may be used by others).

